In [1]:
#Tässä notebookissa käsitellään vanhaa Savonian opinnäytetyökyselyä. Tarkoituksena on selvittää, että eroaako tyytyväisyys ohjaukseen 
#eri koulutusaloilla.   

#ladataan aluksi data Excelistä tibleen.

library(readxl)

data <- read_excel("C:\\Users\\Installer\\Desktop\\opinnäytetyökysely.xlsx", sheet = "Kysely")

print(data)

# A tibble: 242 × 42
   Aikaleima           `Kuinka löysit aiheesi?` Opinnäytetyöni oli hankkeistet…¹
   <chr>               <chr>                    <chr>
 1 26.10.2015 21:11:28 Itse                     Kyllä
 2 26.10.2015 21:11:28 Itse                     Ei
 3 26.10.2015 21:11:28 Itse                     Kyllä
 4 26.10.2015 21:11:28 Itse                     Ei
 5 26.10.2015 21:11:28 Työharjoittelupaikasta   Kyllä
 6 26.10.2015 21:11:28 Itse                     Ei
 7 26.10.2015 21:11:28 Muu                      Ei
 8 26.10.2015 21:11:28 Itse                     Kyllä
 9 26.10.2015 21:11:28 Itse                     Ei
10 26.10.2015 21:11:28 Itse                     Ei
# ℹ 232 more rows
# ℹ abbreviated name: ¹​`Opinnäytetyöni oli hankkeistettu`
# ℹ 39 more variables:
#   `Oliko työsi teoreettinen vai käytännöllinen? Teoreettinen (1) - Käytännöllinen (5)` <dbl>,
#   `Pystyin itse vaikuttamaan aiheen valintaan` <dbl>,
#   `Olin innostunut opinnäytetyötä tehdessäni` <dbl>,
#   `Pystyin itse vaikuttamaan opinnäytetyöni ohjaajan valintaan` <dbl>, …

In [2]:
#Selvitetään seuraavaksi vastaajien määrä sukupuolittain eri koulutusaloilla. Tehdään tämä ristiintaulukoinnin avulla. 
#Kirjasto CrossTable sisältää paljon muutakin ristiintaulukointiin liittyvää. Kannattaa tutustua.

table(data$Sukupuoli, data$Opiskeluala)

         Kulttuuri Liiketalous Tekniikka
  Mies          14          20        52
  Nainen       110          44         2

In [3]:
#Ja toisinpäin.

table(data$Opiskeluala, data$Sukupuoli)

              Mies Nainen
  Kulttuuri     14    110
  Liiketalous   20     44
  Tekniikka     52      2

In [4]:
#Tyytyväisyyttä ohjaukseen kysytään useassa kysymyksessä (Excelin sarakkeet H,N,O,Q-U). Lähestymisnäkökulmasta
#riippuen myös muita väittämiä voi ottaa mukaan, mutta käytetään näitä. 
#Tehdään valituista väittämistä ns. summamuuttuja, eli lasketaan vastaajakohtainen keskiarvo näistä.

library(dplyr)

data <- data %>%
  rowwise() %>%
  mutate(Kokonaistyytyväisyys = mean(c_across(all_of(c("Sain riittävästi ohjausta","Ohjaajani panos tuki työtäni", "Saamani ohjaus oli asiantuntevaa", 
    "Saamani ohjaus oli asiantuntevaa", "Saamani ohjaus oli motivoivaa", "Työni ohjaaja vastasi nopeasti tiedusteluihini",
    "Ohjaustilanteet eivät tuntuneet minusta pelottavilta", "Ohjaajaani oli helppo lähestyä", "Luotin ohjaajani neuvoihin"))),
                            na.rm = TRUE))

data

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

    Aikaleima           Kuinka löysit aiheesi?
1   26.10.2015 21:11:28 Itse
2   26.10.2015 21:11:28 Itse
3   26.10.2015 21:11:28 Itse
4   26.10.2015 21:11:28 Itse
5   26.10.2015 21:11:28 Työharjoittelupaikasta
6   26.10.2015 21:11:28 Itse
7   26.10.2015 21:11:28 Muu
8   26.10.2015 21:11:28 Itse
9   26.10.2015 21:11:28 Itse
10  26.10.2015 21:11:28 Itse
11  26.10.2015 21:11:28 Työharjoittelupaikasta
12  26.10.2015 21:11:28 Itse
13  26.10.2015 21:11:28 Itse
14  26.10.2015 21:11:28 Itse
15  26.10.2015 21:11:28 Ohjaajaltani
16  26.10.2015 21:11:28 Itse
17  26.10.2015 21:11:28 Itse
18  26.10.2015 21:11:28 Itse
19  26.10.2015 21:11:28 Muu
20  26.10.2015 21:11:28 Muu
21  26.10.2015 21:11:28 Muu
22  26.10.2015 21:11:28 Itse
23  26.10.2015 21:11:28 Itse
24  26.10.2015 21:11:28 Työharjoittelupaikasta
25  26.10.2015 21:11:29 Itse
26  26.10.2015 21:11:29 Itse
27  26.10.2015 21:11:29 Ohjaajaltani
28  26.10.2015 21:11:29 Työharjoittelupaikasta
29  26.10.2015 21:11:29 Työharjoittelupaikasta
30  26.10.2015 21:11:29 Itse
⋮   ⋮                   ⋮
213 26.10.2015 21:11:39 Työelämästä (ei työharjoittelupaikka)
214 26.10.2015 21:11:39 Ohjaajaltani
215 26.10.2015 21:11:39 Työelämästä (ei työharjoittelupaikka)
216 26.10.2015 21:11:39 Ohjaajaltani
217 26.10.2015 21:11:39 Työharjoittelupaikasta
218 26.10.2015 21:11:39 Työharjoittelupaikasta
219 26.10.2015 21:11:39 Itse
220 26.10.2015 21:11:39 Työelämästä (ei työharjoittelupaikka)
221 26.10.2015 21:11:39 Muu
222 26.10.2015 21:11:39 Työharjoittelupaikasta
223 26.10.2015 21:11:39 Työharjoittelupaikasta
224 26.10.2015 21:11:39 Muu
225 26.10.2015 21:11:39 Työharjoittelupaikasta
226 26.10.2015 21:11:39 Työharjoittelupaikasta
227 26.10.2015 21:11:39 Työelämästä (ei työharjoittelupaikka)
228 26.10.2015 21:11:39 Työharjoittelupaikasta
229 26.10.2015 21:11:39 Itse
230 26.10.2015 21:11:39 Itse
231 26.10.2015 21:11:39 Itse
232 26.10.2015 21:11:39 Työharjoittelupaikasta
233 26.10.2015 21:11:39 Työelämästä (ei työharjoittelupaikka)
234 26.10.2015 21:11:40 Muu
235 26.10.2015 21:11:40 Työelämästä (ei työharjoittelupaikka)
236 26.10.2015 21:11:40 Työharjoittelupaikasta
237 26.10.2015 21:11:40 Muu
238 26.10.2015 21:11:40 Työharjoittelupaikasta
239 26.10.2015 21:11:40 Työharjoittelupaikasta
240 26.10.2015 21:11:40 Itse
241 26.10.2015 21:11:40 Itse
242 26.10.2015 21:11:40 Työelämästä (ei työharjoittelupaikka)
    Opinnäytetyöni oli hankkeistettu
1   Kyllä
2   Ei
3   Kyllä
4   Ei
5   Kyllä
6   Ei
7   Ei
8   Kyllä
9   Ei
10  Ei
11  Ei
12  Ei
13  Kyllä
14  Ei
15  Ei
16  Ei
17  Ei
18  Ei
19  Ei
20  Ei
21  Ei
22  Ei
23  Ei
24  Ei
25  Kyllä
26  Ei
27  Kyllä
28  Kyllä
29  Kyllä
30  Ei
⋮   ⋮
213 Kyllä
214 Kyllä
215 Ei
216 Kyllä
217 Kyllä
218 Kyllä
219 Kyllä
220 Kyllä
221 Kyllä
222 Kyllä
223 Kyllä
224 Kyllä
225 Kyllä
226 Kyllä
227 Kyllä
228 Kyllä
229 Kyllä
230 Kyllä
231 Ei
232 Kyllä
233 Kyllä
234 Kyllä
235 Kyllä
236 Kyllä
237 Kyllä
238 Kyllä
239 Kyllä
240 Kyllä
241 Kyllä
242 Kyllä
    Oliko työsi teoreettinen vai käytännöllinen? Teoreettinen (1) - Käytännöllinen (5)
1   3
2   1
3   3
4   4
5   2
6   4
7   4
8   4
9   3
10  3
11  2
12  5
13  4
14  3
15  1
16  3
17  4
18  5
19  3
20  4
21  3
22  4
23  4
24  5
25  2
26  4
27  2
28  5
29  5
30  3
⋮   ⋮
213 5
214 4
215 5
216 4
217 4
218 4
219 4
220 4
221 2
222 4
223 4
224 2
225 3
226 5
227 4
228 3
229 4
230 2
231 3
232 4
233 4
234 4
235 3
236 3
237 2
238 4
239 3
240 4
241 3
242 3
    Pystyin itse vaikuttamaan aiheen valintaan
1   5
2   5
3   5
4   5
5   4
6   5
7   5
8   5
9   5
10  5
11  5
12  5
13  4
14  5
15  5
16  5
17  5
18  5
19  5
20  5
21  5
22  4
23  2
24  4
25  5
26  5
27  3
28  4
29  5
30  5
⋮   ⋮
213 4
214 4
215 2
216 4
217 4
218 5
219 5
220 1
221 5
222 1
223 4
224 4
225 5
226 5
227 4
228 4
229 5
230 4
231 1
232 2
233 4
234 3
235 5
236 4
237 4
238 4
239 4
240 5
241 5
242 2
    Olin innostunut opinnäytetyötä tehdessäni
1   5
2   5
3   4
4   5
5   2
6   5
7   5
8   5
9   5
10  3
11  4
12  4
13  4
14  5
15  5
16  2
17  4
18  5
19  5
20  4
21  5
22  4
23  5
24  5
25  4
26  5
27  4
28  5
29  4
30  5
⋮   ⋮
213 5
214 4
215 4
216 5
217 4
218 5
219 5
220 4
221 5
222 4
223 5
224 4
225 5
226 5
227 3
228 5
229 5
230 5
231 4
232 4
233 5
234 5
235 4
236 5
237 4
238 5
239 5
240 5
241 5
242 5
    Pystyin itse vaikuttamaan opinnäytetyöni ohjaajan valintaan
1   5
2   3
3   1
4   3
5   4
6   4
7   4
8   2
9   5
10  1
11  5
12  3
13  2
14  4
15  4
16  2
17  2
18  5
19  1
20  1
21  3
22  5
23  5
24  5
25  1
26  1
27  1
28  2
29  4
30  5
⋮   ⋮
213 5
214 4
215 4
216 3
217 5
218 5
219 1
220 1
221 4
222 1
223 5
224 4
225 4
226 4
227 2
228 5
229 5
230 2
231 1
232 5
233 3
234 5
235 4
236 4
237 4
238 5
239 5
240 1
241 1
242 5
    Sain riittävästi ohjausta Hankin itse aktiivisesti tietoa työni aiheesta
1   1                         5
2   1                         4
3   5                         4
4   2                         4
5   4                         4
6   2                         4
7   2                         3
8   5                         5
9   5                         5
10  2                         4
11  2                         4
12  3                         4
13  3                         4
14  3                         5
15  4                         5
16  3                         5
17  3                         4
18  2                         4
19  3                         5
20  4                         2
21  1                         5
22  5                         4
23  4                         5
24  1                         5
25  4                         4
26  4                         4
27  4                         4
28  5                         5
29  5                         4
30  5                         5
⋮   ⋮                         ⋮
213 5                         5
214 5                         5
215 4                         4
216 4                         5
217 5                         5
218 4                         5
219 4                         5
220 1                         3
221 1                         5
222 3                         5
223 4                         5
224 2                         4
225 5                         5
226 4                         4
227 4                         4
228 5                         5
229 5                         5
230 2                         4
231 2                         5
232 4                         5
233 4                         4
234 4                         4
235 5                         4
236 5                         4
237 2                         4
238 4                         5
239 5                         5
240 4                         5
241 5                         5
242 2                         4
    Tutkimusaiheeni kiinnosti minua ⋯
1   5                               ⋯
2   4                               ⋯
3   5                               ⋯
4   5                               ⋯
5   3                               ⋯
6   5                               ⋯
7   5                               ⋯
8   5                               ⋯
9   5                               ⋯
10  3                               ⋯
11  4                               ⋯
12  4                               ⋯
13  4                               ⋯
14  5                               ⋯
15  5                               ⋯
16  4                               ⋯
17  4                               ⋯
18  5                               ⋯
19  5                               ⋯
20  4                               ⋯
21  5                               ⋯
22  4                               ⋯
23  5                               ⋯
24  5                               ⋯
25  5                               ⋯
26  5                               ⋯
27  4                               ⋯
28  5                               ⋯
29  4                               ⋯
30  5                               ⋯
⋮   ⋮                               ⋱
213 5                               ⋯
214 5                               ⋯
215 4                               ⋯
216 4                               ⋯
217 5                               ⋯
218 5                               ⋯
219 5                               ⋯
220 4                               ⋯
221 5                               ⋯
222 5                               ⋯
223 5                               ⋯
224 4                               ⋯
225 5                               ⋯
226 5                               ⋯
227 4                               ⋯
228 5                               ⋯
229 5                               ⋯
230 4                               ⋯
231 4                               ⋯
232 4                               ⋯
233 5                               ⋯
234 4                               ⋯
235 4                               ⋯
236 4                               ⋯
237 4                               ⋯
238 5                               ⋯
239 5                               ⋯
240 5                               ⋯
241 5                               ⋯
242 4                               ⋯
    Ohjaajan tuki opinnäytetyön eri vaiheissa:johtopäätösten ja yhteenvedon tekemisessa
1   2
2   1
3   4
4   4
5   4
6   2
7   3
8   5
9   5
10  4
11  3
12  4
13  4
14  5
15  3
16  2
17  4
18  3
19  3
20  4
21  2
22  4
23  4
24  3
25  4
26  4
27  5
28  5
29  4
30  5
⋮   ⋮
213 5
214 4
215 2
216 3
217 4
218 2
219 2
220 1
221 1
222 4
223 3
224 4
225 2
226 4
227 3
228 3
229 5
230 3
231 1
232 3
233 3
234 3
235 5
236 4
237 4
238 3
239 3
240 2
241 4
242 4
    Ohjaajan tuki opinnäytetyön eri vaiheissa:raportoinnissa Thesis grade
1   4                                                        NA
2   4                                                        NA
3   5                                                        NA
4   4                                                         5
5   4                                                        NA
6   4                                                        NA
7   4                                                         5
8   5                                                         4
9   5                                                        NA
10  4                                                        NA
11  3                                                        NA
12  5                                                        NA
13  4                                                        NA
14  5                                                         5
15  3                                                        NA
16  2                                                        NA
17  4                                                        NA
18  4                                                         5
19  1                                                        NA
20  3                                                        NA
21  2                                                         3
22  5                                                         5
23  5                                                        NA
24  3                                                        NA
25  3                                                        NA
26  3                                                        NA
27  4                                                         4
28  5                                                         3
29  5                                                        NA
30  5                                                         4
⋮   ⋮                                                        ⋮
213 5                                                        NA
214 5                                                        NA
215 3                                                        NA
216 4                                                         4
217 4                                                         4
218 4                                                        NA
219 5                                                        NA
220 3                                                        NA
221 2                                                        NA
222 4                                                        NA
223 3                                                        NA
224 2                                                         4
225 2                                                         5
226 5                                                        NA
227 3                                                        NA
228 3                                                         4
229 5                                                         4
230 4                                                        NA
231 1                                                        NA
232 4                                                        NA
233 3                                                        NA
234 3                                                         5
235 5                                                        NA
236 5                                                        NA
237 2                                                         4
238 3                                                        NA
239 3                                                         4
240 5                                                        NA
241 5                                                         4
242 5                                                         4
    Opinnäytetyön tekemiseen kulunut aika ensimmäisistä aihekaavailuista työn valmistumiseen:kuukautta
1   24
2   11
3    7
4    5
5   14
6    9
7   12
8   12
9   12
10  12
11   4
12   9
13   4
14  12
15   4
16   4
17   4
18  18
19  10
20   8
21  12
22   7
23  16
24   2
25  12
26  14
27  24
28   2
29  30
30   7
⋮   ⋮
213  4.0
214  5.0
215  6.0
216  4.0
217  5.0
218  4.0
219  8.0
220  4.0
221  4.0
222  3.5
223  9.0
224  4.0
225 12.0
226  8.0
227  3.0
228  6.0
229  3.0
230  4.0
231  6.0
232  4.0
233  9.0
234  5.0
235  6.0
236  4.0
237  4.0
238  9.0
239  6.0
240  8.0
241  3.0
242  6.0
    Opinnäytetyön tekemisaika työviikkoina (40 h) aihekuvauksen tekemisestä työn valmistumiseen:työviikkoa
1    20
2     7
3    28
4    17
5    10
6    12
7    10
8    17
9    20
10   17
11   12
12   NA
13   10
14   NA
15   14
16   24
17   16
18    8
19   10
20    7
21   14
22   30
23   10
24    8
25   48
26   NA
27  104
28   30
29   NA
30   NA
⋮   ⋮
213 12
214  7
215  3
216  7
217 10
218 13
219 32
220  5
221 15
222  7
223 16
224 14
225 15
226 30
227 10
228 21
229 16
230 13
231 NA
232 15
233 25
234 NA
235  3
236 10
237 14
238 16
239 21
240 32
241 15
242 11
    Oliko työ parityö? Opiskeluala Sukupuoli Ikä Kokonaistyytyväisyys
1   0                  Kulttuuri   Nainen    23  2.875
2   0                  Kulttuuri   Nainen    27  2.500
3   0                  Kulttuuri   Nainen    22  3.875
4   0                  Kulttuuri   Nainen    26  3.625
5   0                  Kulttuuri   Mies      36  4.250
6   0                  Kulttuuri   Nainen    23  2.500
7   1                  Kulttuuri   Nainen    26  3.625
8   0                  Kulttuuri   Nainen    22  5.000
9   0                  Kulttuuri   Nainen    24  5.000
10  0                  Kulttuuri   Nainen    23  3.625
11  0                  Kulttuuri   Nainen    23  2.625
12  0                  Kulttuuri   Nainen    23  3.500
13  0                  Kulttuuri   Mies      28  3.000
14  0                  Kulttuuri   Nainen    24  3.750
15  0                  Kulttuuri   Nainen    30  4.625
16  0                  Kulttuuri   Nainen    23  3.500
17  1                  Kulttuuri   Nainen    23  3.875
18  1                  Kulttuuri   Nainen    27  3.375
19  0                  Kulttuuri   Nainen    26  4.000
20  0                  Kulttuuri   Mies      25  4.125
21  0                  Kulttuuri   Nainen    26  2.875
22  0                  Kulttuuri   Nainen    24  4.875
23  0                  Kulttuuri   Nainen    30  4.500
24  0                  Kulttuuri   Mies      51  2.500
25  0                  Kulttuuri   Nainen    25  4.125
26  0                  Kulttuuri   Nainen    26  4.750
27  0                  Kulttuuri   Nainen    28  4.000
28  0                  Kulttuuri   Nainen    42  4.875
29  0                  Kulttuuri   Nainen    23  5.000
30  0                  Kulttuuri   Nainen    22  4.750
⋮   ⋮                  ⋮           ⋮         ⋮   ⋮
213 0                  Tekniikka   Mies      48  5.000
214 0                  Tekniikka   Mies      27  5.000
215 0                  Tekniikka   Mies      24  3.750
216 0                  Tekniikka   Mies      24  4.375
217 0                  Tekniikka   Mies      23  4.625
218 0                  Tekniikka   Mies      24  4.375
219 0                  Tekniikka   Mies      33  4.375
220 0                  Tekniikka   Mies      35  1.875
221 0                  Tekniikka   Mies      24  2.750
222 0                  Tekniikka   Mies      24  2.750
223 0                  Tekniikka   Mies      24  4.625
224 0                  Tekniikka   Mies      25  3.375
225 0                  Tekniikka   Mies      25  4.750
226 0                  Tekniikka   Nainen    23  4.250
227 0                  Tekniikka   Mies      23  4.375
228 0                  Tekniikka   Mies      23  4.750
229 0                  Tekniikka   Mies      26  5.000
230 0                  Tekniikka   Mies      24  3.625
231 0                  Tekniikka   Mies      23  3.250
232 0                  Tekniikka   Mies      24  3.875
233 1                  Tekniikka   Mies      41  4.125
234 0                  Tekniikka   Mies      23  4.500
235 0                  Tekniikka   Mies      29  4.625
236 0                  Tekniikka   Mies      25  4.625
237 0                  Tekniikka   Mies      25  3.375
238 0                  Tekniikka   Mies      24  4.625
239 0                  Tekniikka   Mies      23  4.750
240 0                  Tekniikka   Mies      33  4.375
241 0                  Tekniikka   Mies      25  4.875
242 0                  Tekniikka   Mies      27  4.625

In [5]:
#Tarkastellaan nyt kokonaistyytyväisyyden keskiarvoa koulutusaloittain. Tablea ei voi käyttää suoraan.

#library(dplyr)
library(tidyr)

ristiin <- data %>%
  group_by(Opiskeluala, Sukupuoli) %>%        # ristiintaulukoinnin ryhmät
  summarise(Keskiarvo = mean(Kokonaistyytyväisyys, na.rm = TRUE))

ristiin

`summarise()` has grouped output by 'Opiskeluala'. You can override using the `.groups` argument.

  Opiskeluala Sukupuoli Keskiarvo
1 Kulttuuri   Mies      3.875000
2 Kulttuuri   Nainen    4.002273
3 Liiketalous Mies      4.200000
4 Liiketalous Nainen    3.420455
5 Tekniikka   Mies      4.149038
6 Tekniikka   Nainen    4.250000

In [6]:
#Muokataan tulostuksesta parempi. 

ristiin2 <- ristiin %>%
  pivot_wider(
    names_from = Sukupuoli,
    values_from = Keskiarvo
  )

ristiin2

  Opiskeluala Mies     Nainen
1 Kulttuuri   3.875000 4.002273
2 Liiketalous 4.200000 3.420455
3 Tekniikka   4.149038 4.250000

In [7]:
#Näyttä siltä, että varsinkin tekniikan alan opiskelijat ovat tyytyväisempiä ohjaukseen kuin liiketalouden alan opiskelijat. 
#Tutkitaan seuraavaksi, että onko se todella näin. Ts. otetaan selville, että onko ristiintaulukoinnissa havaittu ero
#tilastollisesti merkittävä vai johtuuko se sattumasta.

#Erotetaan liiketalouden ja tekniikan opiskelijat omiksi vektoreikseen. Otetaan mukaan ainoastaan kokonaistyytyväisyyden sarake.
#Tämä selkeyttää analyysia. 

liiketalous<- data %>%
  filter(Opiskeluala == "Liiketalous") %>%
  pull(Kokonaistyytyväisyys)

tekniikka <- data %>%
  filter(Opiskeluala == "Tekniikka") %>%
  pull(Kokonaistyytyväisyys)

summary(liiketalous)
summary(tekniikka)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.875   2.875   3.938   3.664   4.406   5.000

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.875   3.781   4.375   4.153   4.625   5.000

In [8]:
#Tutkitaan seuraavaksi, että ovatko lasketut keskiarvot normaalisti jakautuneita. Normaalisuus on edellytys t-testien käyttämiselle.

#Käytetään testaamiseen Shapiron-Wilkin testiä, jota voidaan käyttää, kun havaintoja on vähän. Sitä voidaan käyttää
#noin 2000 havaintomäärään asti. Muodostetaan hypoteesit: H0: Aineisto on normaalisti jakautunut. 
#H1: Aineisto ei ole normaalisti jakautunut. 

shapiro.test(liiketalous)
shapiro.test(tekniikka)

	Shapiro-Wilk normality test

data:  liiketalous
W = 0.92665, p-value = 0.0009528

	Shapiro-Wilk normality test

data:  tekniikka
W = 0.86042, p-value = 1.582e-05

In [9]:
#Nyt molemmissa tapauksissa p-arvo on todella pieni ja testi antaa 95 % luottamuksella suositukseksi hylätä H0.
#Kumpikaan datoista ei siis ole normaalisti jakautunut, eikä t-testejä voida käyttää. Käydään kuitenkin seuraavaksi lävitse, 
#miten edettäisiin, jos data olisivat normaalisti jakautuneita. 

#Testataan seuraavaksi Levenen testillä ovatko varianssit yhtä suuret, jotta tiedetään mitä t-testiä käytetään. 

#Levenen testissä käytettävät hypoteesit: H0: Varianssit ovat yhtä suuret. H1: Varianssit eivät ole yhtä suuret. 


#Asenna ensin paketti car.

library(car)

grp <- factor(c(rep("L", length(liiketalous)),
                rep("T", length(tekniikka))))

leveneTest(c(liiketalous, tekniikka), grp, center = mean)

#center = mean -argumentilla käytetään samaa logiikkaa kuin Julia oletuksena. Toinen mahdollisuus olisi canter = median (oletus).

Loading required package: carData


Attaching package: 'car'


The following object is masked from 'package:dplyr':

    recode

      Df  F value  Pr(>F)
group   1 3.808957 0.05338961
      116       NA         NA

In [10]:
#Testin perusteella nollahypoteesia ei voi hylätä (p = 0,0534) ja varianssit voidaan olettaa yhtä suuriksi. 

#H0: Jakaumat ovat samanlaiset, eli liiketalouden ja tekniikan opiskelijoiden tyytyväisyydessä ei ole eroa. 
#H1: Jakaumat ovat erilaiset, eli liiketalouden ja tekniikan opiskelijoiden tyytyväisyydessä on eroa.

t.test(liiketalous, tekniikka, var.equal = TRUE)

#Mikäli varianssit eivät olisi olleet yhtä suuria, olisimme voineet käyttää Welchin t-testiä, joka ei edellytä
#yhtäsuuria variansseja. 

#t.test(liiketalous, tekniikka, var.equal = FALSE)

	Two Sample t-test

data:  liiketalous and tekniikka
t = -3.0934, df = 116, p-value = 0.00248
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.8016263 -0.1758042
sample estimates:
mean of x mean of y
 3.664062  4.152778

In [11]:
#Nyt p-arvo on 0,0025 ja 95% varmuudella voimme hylätä H0:n. Tyytyväisyydessä ohjaukseen on siis tilastollisesti
#merkittävä ero. Testi tehtiin kuitenkin kaksisuuntaisena, joten ero voisi olla molempiin suuntiin. 

#Keskiarvosta kuitenkin nähdään, että tekniikan opiskelijat ovat tyytyväisempiä ohjaukseen, joten tämä voidaan ottaa
#johtopäätökseksi. Olisi myös mahdollista tehdä ns. yksisuuntainen t-testi, mutta se sivuutetaan. 

#Koska datat eivät olleet normaalisti jakautuneita, käytetään Mann-Whitneyn U-testiä (R:ssä Wilcox argumentilla paired = FALSE), 
#joka ei edellytä normaalisuutta. Sitä voidaan käyttää myös normaalisti jakautuneelle datalle, mutta t-testit ovat parempi
#valinta, jos käyttöedellytykset täyttyvät. 

#H0: Jakaumat ovat samanlaiset, eli liiketalouden ja tekniikan opiskelijoiden tyytyväisyydessä ei ole eroa. 
#H1: Jakaumat ovat erilaiset, eli liiketalouden ja tekniikan opiskelijoiden tyytyväisyydessä on eroa.

wilcox.test(liiketalous,tekniikka, alternative = "two.sided", paired = FALSE)

	Wilcoxon rank sum test with continuity correction

data:  liiketalous and tekniikka
W = 1176, p-value = 0.002821
alternative hypothesis: true location shift is not equal to 0

In [12]:
#Testin tulosten perusteella päädytään samaan johtopäätökseen kuin t-testiä käytettäessä. Huomataan, että vaikka t-testin
#käyttöedellytykset eivät toteutuneet, niin siitä huolimatta se johti oikeaan lopputulokseen. Näin ei kuitenkaan aina ole. 

#HUOM! Mikäli datat olisivat olleet normaalisti jakautuneita ja varianssit yhtä suuria, niin Mann-Whitneyä ei olisi tarvinnut tehdä.